# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-19 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='name',
            field=models.CharField(default='sender', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
